/* AUTO-GEN bởi scripts/gen-grids-from-ref.py — grid game downscale từ ảnh mẫu */
globalThis.REF_GRIDS = [
  {
    "key": "tanLua",
    "line": "lua",
    "stage": 1,
    "size": 32,
    "palette": "fire",
    "grid": [
      "ddf..............d.............",
      "drfd............fff.......ll...",
      "drlfd.........dfrrfv.....yyf...",
      "dvfrdd.......dfrddfv....lyy....",
      "dddrrd......frrddodv...fyYyl...",
      "dfddrdvddd.drrddfodv...dyYYyl..",
      "dffvddfdfrddrddflodv....lYYYyf.",
      "dfldvdrlrrfffdfllvdv....fYYYyf.",
      "odldfrrlrrrrddlhfdd....fyYYYl..",
      "vdffllllrrrrrdfhddv..flyYYYYyf.",
      ".vdrrllrrrrrrrddfv..fyYYYYyYyr.",
      ".vfrrrrrrrrrrrfddv..fyyYYyyYYyd",
      ".dddrrrrrfdfrrrdo..oryyYyyyYYyv",
      ".dftdrrrrfkkfrrfo..drryyyyyYyyv",
      "dffkvrrrftktlrrfdd.drrrrryYYryv",
      "dftkfrrrfoktllrfdo.dfrrrryYlrro",
      "klCffflhhftChChlooovfrrrrlrrrd.",
      "vdhhodChhhhhhhCfvddddffrrrfffv.",
      "..dlhhhhhhhhhfvvfrrrfdffffffd..",
      "...vflllhhldddfrrrrrrddfffddd..",
      ".....ooffllfdfrrrrrrrfvoovo....",
      "......lhhhlhrrrrrrrrffo........",
      ".....olChhhhrrrrrfffffo........",
      "......dhCCClrrrffldfffdv.......",
      "......vdlChfrrrdllodffdv.......",
      "......vdfdldrrrvvooodfdv.......",
      ".......drdoofrrvdv..ofdv.......",
      ".......vfdv.drfodo..ofdd.......",
      "......ddfv..dfdov..vdfo........",
      "......vddo.vfrv.....ooo........",
      "......ooo..vffo................",
      "...........dvv................."
    ]
  },
  {
    "key": "tanLua-back",
    "line": "lua",
    "stage": 1,
    "size": 32,
    "palette": "fire",
    "grid": [
      ".............d...............dd.",
      "............ffdd...........dfrd.",
      "...f........frfdd.........vfrrdv",
      "...ly.......frrfdd.......dfrrffv",
      "...fyyf.....frffffd......frrrffv",
      "...lyyl.....drffffdo.ffdfrrrfffv",
      "...yyYyf....dfffffddfrddrrrrfffv",
      "..lyYYyd....dffffdfrrrrdrrrfffdv",
      ".fyYYyf.....odffdfrrrrrfrrffffdo",
      ".fyYYyl.....oddddfrrrfffffffffv.",
      ".dlYYYylf....oddfffffffffffffdv.",
      ".lyYYYYYyl....odffffffffffffdo..",
      "dyYYyYYYyyf...odffffffffffffdv..",
      "fYYYyyYYyyyd..vffffffffffffffdv.",
      "dYYYyyyYYyyfvvdfffffffffffffffdo",
      "dyyYyyyyylrrdfvdffffffffffffffdv",
      "vyryYyrrrrrfddovfffffffffffrhld.",
      "orrlyyrrrrrfdv.vddffffffffrhfdd.",
      "odrrrrrrrrffdvddfrrrrffdfffdv...",
      ".vfrrrrrrfffffrrrrrrrrrfff......",
      ".vdfffrfffffdrrrrrrrrrrfflo.....",
      "...vdffffffddfrrrrrrrrffdfo.....",
      "....vdddddddffrrrrrrrffffv......",
      "......voovdfffffrfffffffdo......",
      "........vdvfhdffffdlhfffdv......",
      ".......odddvodffffvlvdffd.......",
      ".......odddo.dfffdooovfrv.......",
      ".......oddo..odddodd.ddfv.......",
      ".......odfo..odfdodvvvdfv.......",
      "........odvo..vdfovo..odvo......",
      "........vkv...vvddv....oo.......",
      "...............dovv............."
    ]
  },
  {
    "key": "tanLua-shiny",
    "line": "lua",
    "stage": 1,
    "size": 32,
    "palette": "fireShiny",
    "grid": [
      ".dd...............vv............",
      ".dfd............ddddd......dyd..",
      ".dffd..........vffffv......yr...",
      "ddvfdd........dffdodv....dyyr...",
      "vdodfdv......dffvdodv....ryyrd..",
      "dddodfvvddd.vffoododv....rYYyr..",
      "vdtddddddddvdfvodtodv....dyYYyr.",
      "ddftvkdffffdddodttddd....drYYYr.",
      "dvdtdffffffffdodtdvd.....rYYYyv.",
      ".dddflffffffffdotddv...ryYYYYyr.",
      ".vvdfffffffffffvodvo..ryYYYYYYrd",
      "..vffffffffffffdddo..dyyyYYyYYyr",
      ".ddddfffffddffffdo...dryYYyyYYYy",
      ".ddfvffffddodfffdo..ddryYyyyYYyy",
      "dfddvdfffvfofdffddv.odfrrdryYyrr",
      "ddfrkffffvodffffdvv.vdffdfryYrrd",
      ".dCldffflfdfllllfoo.oddffffrrddv",
      ".dfCdofCllllllllddvvdvddddfddddo",
      "..odfflllllllfdvvdffffdvddddddv.",
      "....vdfffllfdvvddffffffvdddddd..",
      "......ovdfffddddffffffdvooooo...",
      "......vffffffdfffffffdddo.......",
      "......vfllllffffffddddddv.......",
      "......vdllllffffddfdddddv.......",
      ".......ddflldfffdffdvdddo.......",
      ".......ddddddfffdovo.vddo.......",
      ".......vdfvoodffovd..ovdo.......",
      ".......vddd.odfdovo..dddo.......",
      ".......dddv.odddoov..vfdv.......",
      ".......vddv.odfvd....vov........",
      ".......oov..dffd................",
      "............dddd................"
    ]
  },
  {
    "key": "bongBot",
    "line": "lua",
    "stage": 2,
    "size": 40,
    "palette": "fire",
    "grid": [
      "........ff...........v.........",
      "...dd...flf.........ff.........",
      "...rf....flf.f.....ffd.........",
      "..vlyd...rrrrld..dflrfv........",
      "..dfyyd.ryyryr..dllrrfo........",
      "..fdfyrryYyyl.dfyfvdrv.........",
      "..dddyyyYYyyrvlYfvdffv.........",
      "..vfdlyyYYYyrfYldfflf.....ff...",
      "..ofddlyYYylyYyvfrfyf.....drf..",
      "..vfdfYyyyyyYyyfdffyd......rrf.",
      "...dfyyyyyyyyyyYrdlf......frrf.",
      "...oyYyyyyyyYYyyyylv......fyyr.",
      "...fdyyyyyyYydfyYlo.......lyyld",
      ".vfyCoyYyyyddCfyyylfd..f.fyyYl.",
      ".vyYhffyyyfftcyyyyYl..llfryYyf.",
      "..vlYyYyyyYyyYYYYydd.rlrryyYyff",
      "..ohfvdyYYYYYYYYYYhddryyyyYyyrf",
      "..dlddlYYYhfYYYYhdo.frYyyYYlrd.",
      "....vlhlfflYYhldflv.fryYYYyrd..",
      ".....ddlhhhYhllhhfd.flyYyYyr...",
      "....vlYhfffyyhYhyyfdryYyYYyrd..",
      "....dlYYYhhhYYYYYYYldyyryyyyf..",
      "....ddlYYYYYYYYylYyYyflryYyyrd.",
      "...dlyyYYYYYYhYlfddlyfdryYyyld.",
      "..dfrldllYYYhflyyvdrldfrYyyyyd.",
      "dfrlrfvvylYYfyyyfdrrfdryYyyYld.",
      "dfrfdo.oYylhlyYydrrrdrryyryYf..",
      "dvvd...dYYlfyyYfdrrdfrrrryyyd..",
      "......fyyyyyyyyydoddrrrrryyfd..",
      ".....vdyyyYyyyyyydyldrrrrrrv...",
      ".....dfyYyyYYYyyYYrydrrrrfd....",
      ".....drylyyyyyYyyyrrdrrrfv.....",
      ".....dlrryydkvlYrrrrvdddv......",
      ".....drryyv...odrrrrd..........",
      "......ofrrdv...ovfrrfv.........",
      ".......drrd......odrfd.........",
      ".....vdrrfo.......vfrd.........",
      "....vfrrfv........orrro........",
      "....vddfv..........frfo........",
      ".....kkk...........ooo........."
    ]
  },
  {
    "key": "bongBot-back",
    "line": "lua",
    "stage": 2,
    "size": 40,
    "palette": "fire",
    "grid": [
      "..........d..........ff.........",
      "..........fd........flf....f....",
      "..........dfd.......lr....drd...",
      ".........dfrrdd..llfylf..dfrd...",
      ".........vfrrrfd.fyyyylf.fyrd...",
      "..........drrryld.fyyyyffyrrfv..",
      "..........vrryyyydflyyyfYyrrrv..",
      "...........fyyyyyfdyyyfyYyyrf...",
      "...lf......fyyyyyyYYyyrYyyyyf...",
      "..rrd......fyyyyyYYYYyyYyyyyf...",
      ".drrf......vfyyyYYYYyyyyyyyyd...",
      ".fryf.......vyyyYYYYyyyyyyyd....",
      ".ryyf.......odyyyyyyyYyyyylfv...",
      "dryyl..d...dfyyyyYYYyyyyyyyyldv.",
      ".fyyyrflf..dfyyyyyyyyyyyyyyydv..",
      "dfyYyyrlrf..dfyyyyyyyyyyyyyfd...",
      "fryYYyrryr..dyyyyyyyyyyyyyyylv..",
      ".fryYYyyyrd..oflyyyyyyylyyyfd...",
      "..fryYYyYrd....dfyyyyyylfdv.....",
      "...fyyYYYrd...vyyyyyyyyyfod.....",
      "...fyYYyYyl..vfYYYyyYyyyyyfo....",
      "..dryyYyyYrddfflfyYYyYyfffd.....",
      "..fyYyYyyYyrddrfyyYyfyfyllyv....",
      ".vryyYYyrYyyrdvyYllyyflylyyydd..",
      ".vrYyyYyryYyyfoyyyyYyyyyvfyyrffd",
      ".vrYyyYyrrrrlrdyyyyyyyylvoddfrrf",
      "..fYyryYyrrrrrdlYyyyyyydv..vdffd",
      "..fyyrryyyrrrrrfyYyyyyydv....dvv",
      "..dfyyrrrrrrrrrryyyyyyyyf.......",
      "...dryrrrrrrrrrrryyyyyyylv......",
      "....frrrrrrrrrrfryyyyyyyrd......",
      ".....frrrrrrrrddfyyyyyffrro.....",
      "......vdffffddfyfvvfyyyfrro.....",
      "..........kvfyyyf..vvfyrrfo.....",
      "..........vfrfdvo...dffrfv......",
      "..........drfvk.....drrfo.......",
      ".........odrfo......vfrrdv......",
      ".........vfrd........dfrrdd.....",
      ".........vddd.........dfffdv....",
      "..........dv...........oooo....."
    ]
  },
  {
    "key": "bongBot-shiny",
    "line": "lua",
    "stage": 2,
    "size": 40,
    "palette": "fireShiny",
    "grid": [
      "...............v...........dd.......",
      "...............vd.........ddd....do.",
      "...............ddv.....d..dd....ddo.",
      "...............vdddv...dddfd...dfdd.",
      "...............dddddv..dfdffd.dffdv.",
      "...............ddddffd..ffflfdClddd.",
      "................ddfflfdddfllffhfddd.",
      "................dfffflfvdffffhlffdd.",
      "................dfffffffllfdlCfffdo.",
      "....ddd..........dffffhcchCfClfffd..",
      "..ddfd...........dfffChhhhCllffffd..",
      "..dfdd...........ddflChhhCCCfffffv..",
      ".ddfdd............vfCCCCCCCClfffvo..",
      ".dffdd..o.......dfflCCCCCCCClfffdd..",
      ".dfffdd.dd.......fffCCCCCCClffffflfo",
      "d.dffffdddd.......dfflCCCClfffffffd.",
      "ddddfffddfdo.....dfffffffffffffffd..",
      ".ddfdfffdffo......ddffffffffffflCfv.",
      "..odfdfffffo.......vdffffffdfffddd..",
      "..dddddffdfv......dflfCffffffdvv....",
      "...dddfffdfdd.....ffCChhlffffdv.....",
      "..ddddflfddfddv..ffffCCfCfffld......",
      ".ddfddflfddffffvdfddfCfffffhCCd.....",
      ".vdfdflfffdffffodfdCffflffffCCfd....",
      ".ddffdflflfdfffdvdfCffCClffdflffvv..",
      ".vdfffflfflfdfffodCCCCCCCffvvdfdddd.",
      "..dflfdfffffdfffddlCCCCCCfdd.ovdffdv",
      "..odflffffffffffffdCCCCCffdv...vdddd",
      "...ddfffffddffffffffClfffffdd...doov",
      "...vdfffdffffffffffffffffffdv.......",
      "....odfffffffffffddffffffdfddv......",
      ".....odfffffffffdddddfffffdddd......",
      ".......dddffffdddffdovdffffddv......",
      "..........dvvvoddfdd...vdfffdd......",
      ".............odfdoo.....dfddd.......",
      ".............offd......dfffd........",
      ".............dffd.......dffdo.......",
      "............vdffv.......odffdd......",
      "............odddd........vfffdo.....",
      ".............ooo..........ovdd......"
    ]
  },
  {
    "key": "bongBot-alt",
    "line": "lua",
    "stage": 2,
    "size": 40,
    "palette": "fire",
    "grid": [
      ".......f.........................",
      "......fr...........o.............",
      "...do.ly.........vff.............",
      "..vfflyyf......vfryf.............",
      "..orffYyf.ff..oflrrf.............",
      "..vdyyyy.dlf.vfydvrf........ff...",
      "..vdfydChyl.vlYdddff........flf..",
      "..ffdylfyyfdfYddfff..........lyd.",
      "..frvlyyYylvyyvffff..........ryl.",
      "..frddyYyylfyvfrfff......d..lyyld",
      "..dyddyYyylyydfrflv.....flllyyyrf",
      "..vffyyyyyyYYYfdff.....dyllyyYyrl",
      "...dYYyryyyyYYYdyd.....fyyyyYYyrf",
      "...fyYyyYyYyyyYyd......dyyyYYyr..",
      "..odlYyYyylvvyYyfo.....dyyyYyyf..",
      "dyftdyYYyfkChyyyyldv..flyYyyYyr..",
      "dyytdyyYyCtCYYYYYYYd.flyyYyyYyld.",
      ".vlyYYyyYYYYYYYYhffCCryYYyryyYyfd",
      ".vydolYYYYYYYYYYfkcwdryyyyrryYyrd",
      "..dvfYYYhfyYYYhlfkWCfryyrrryYyyyd",
      "...dfflllhYYYlvtCwwffrrrrrryYyyyd",
      "....oodfYyyyyyfdtcCofrrrrrryyyyfv",
      "......dlyyyyyyyyfdfyfdrrrrrlryyd.",
      ".....vyyyyyyYYyfdyYYYyfrrrrrryro.",
      "....vdyYyyYYYYYYfyYyyYldrrrrrrf..",
      ".....dYYYYYYyyylfdYyyyydrrrrrfv..",
      ".....fyyYYyyyrfddyYyyYyfdffdd....",
      "....vddyYYylfffYYYyyYyyfovvv.....",
      "......ofyyyldlYyyyllyyyf.........",
      "......vfryyfYyYyflofyyyfv........",
      ".......fffyfYyYyvdvvyyyyd........",
      ".......fyfdvyyYyvfdkfyyyf........",
      ".......dyyfkfyyydfd.vdyrfo.......",
      ".......vfrfkdlyydfo...drfo.......",
      ".......vfrd.vrrddfo...drfo.......",
      ".......vfrd.vrrvfv....drfo.......",
      ".......dffv.drfodo...dfrd........",
      "......vdffd.frdk.....vddd........",
      "......ooov.drrd..................",
      "...........ooo..................."
    ]
  },
  {
    "key": "diemLong",
    "line": "lua",
    "stage": 3,
    "size": 48,
    "palette": "fire",
    "grid": [
      "...........f................................",
      "...........lf...............................",
      ".......fd.lyf.fr............................",
      ".....d.ll.yy..yl............................",
      "....vd.fyfll.lyhvo..........................",
      "....dfvfylylryfdfdlr....................frf.",
      "....dffYyryyyfdrdyyrd....dd............drf..",
      "....dryYyyYyfddddlrd...flyrf...........drf..",
      "...vdrYYYYydfoovfyrf..fyyrrrfdd.........frf.",
      "...vfdyYyyffvovvlYylrryyrfddfffv........ryf.",
      "...vddryrffvovddyyyyyyyrfd...d.....f.dfryyr.",
      "...vfyrrfffoovvlyrfrrrrfd.........rylyyyyyrv",
      "...fyYrrlrrdovdyrrrfdddv.........dryyyyyyrd.",
      "..dryyrylfrrdvrrryrf...d......f..lyyyyyrfd..",
      "..frrllfvrrlldddfrrrddfdd....fl.dyyyyyrfd...",
      "..dfrfdhflYYYhddfdfrrrfd....drf.fyyyyrfd...f",
      ".dfrrrffyYYyfvvdv.vddfd...ffryrdfyyyrrdv..fd",
      "koryhYYYYYYlfddv...vvo...fyyyyrfyyyyrrrd..fd",
      "kfYhyhhYYyydddv.........fyyyyrryyyryyrrfo.ff",
      "..ovddffyyyfdv.........dryyryyyyyyryyrrfdfrf",
      "......ofyyyddv.........fyyrryyyyylryyrffrrrd",
      "......dlyylddv.........fyyryyyyyyrryyrrylrfd",
      "......lYyYfdfdv........drrryrrrrrrryrryrffdv",
      ".....fYYYYhfffdv.......drrrrrrrrrryyryrffdv.",
      "....dYYYYYYlfffdo...oooofrrrrrrrryyyryffd...",
      "....fYYYYYYyfrrrfdvvflrfdvfrrrrryyyrryrfdv..",
      "...fYYYYYyYYfrrrrrlyyyrrrddrrrrryyrryyyrddd.",
      "...fYYYYylyYyfrrrrrrrrrrrrddrrrrrrrryyyfvdd.",
      "..vlyYYYyldyYfrrrrrrrrrrrrfvrrrrrryyyyrdvfd.",
      "..dyfyYYyffdyfrrrrrrfrrrrrfddrryyyyyyrddffv.",
      "..ffofyYyfrrdfrffrrrfrrrrrfdvfryyyrrrrfrrd..",
      "..dv.dyyyffrfrrdfyyyffrrrrfdodfrrrrfffrfd...",
      ".....oflyffrrrffyyfvodrrrrfdovddffffffdd....",
      ".....ovvlldrrrffdvvvvofrrrfdo..vdfffdvo.....",
      "......vooyfrrrdooodddoofrfffd...ovvvo.......",
      "......vdvffrrrdd.ovddvvdfffddd..............",
      ".......vddlrrllfv.ovddv.vddffdo.............",
      ".......vvflfrylf...vddv..vdddfd.............",
      "........oydlyyfv...odvv....vdfd.............",
      "........olfyYyf....odvv....vdfd.............",
      ".........ffyylv....vdv......dfd.............",
      ".........ffyyd....odvo......vfd.............",
      ".........dfYyv...ovdo.......vfd.............",
      "........vdyYf...ovddo......fffd.............",
      ".......vddYYo....ooo......vhYld.............",
      ".......ofYYyo.............vfffd.............",
      ".......flyyd...............vvv..............",
      ".......oodv................................."
    ]
  },
  {
    "key": "diemLong-back",
    "line": "lua",
    "stage": 3,
    "size": 48,
    "palette": "fire",
    "grid": [
      "......................dd............",
      "......................rd............",
      "..................rf.dyl..f.........",
      "..................fyf.yyffl.........",
      "................ovfyl.fyhrl..f......",
      "................odflyrrylyl.ofd.....",
      ".............fff.vfdfyyyryyddrd.....",
      ".............frlrfddfryyYyyffrfo....",
      "......dfffd...drrrrrrrryyYYdfrfv....",
      "....dfryyyyf..dfryyyyrrylyydrrfv....",
      "..dfrrddfryyrfryyyyyyyyyyyydrrfv....",
      "....vv..dfrrrryyyyyyyyyyyyYffrfv....",
      ".........ddfrrrlrrryyyyyyyYldfdov...",
      "..........dddffffrlyryyyrryyvddvd...",
      "............ovvfrlrrryryyyrfdddfdv..",
      "..........fddddrrrffryyrrrrddddflv..",
      "...........dffrrfdddffrfffddddddfdo.",
      "...ddd......ddddvvvvdfddddddddflfdvo",
      "..frf........vvv..vdfdoovddddfyyylfv",
      ".drd..............vvov.vdddddlldddd.",
      ".drfv..................vdfdddld.....",
      ".drrff.................vfrfddld.....",
      ".dfrrrfd...............drrffdlfv....",
      "..dfrrlrfd....dd.......dlrffdlyd....",
      "...vdryyrf....drlf....dryrrfffYyv...",
      ".vd.vrryrfv....fryfvovryrrrrfdyYf...",
      ".dfdvrryyf..drrryyydfllrrrrrfdfyld..",
      "..ddfrryyf.drryyyyyyfrrrrrrrffdfyd..",
      "..ddrryyr..fryyyyryrfrrrrrrrfdddyd..",
      "..drrryyrdfryyyrryrffrrrrffffddvff..",
      "..drryyyydfrrrrryrfvfrrrrdddddfvdf..",
      "..dylyryyrfrrryyyrfvdfrrfddvdfdvdd..",
      "..dryyfyyyyrryyyyrfvddfdfddddfdo.v..",
      "..dfyrfryyyyyyyyyrfdofddfdodfdd.....",
      "odldryfryyyyyyyyyrfdofddfvodffv.....",
      ".dfdryffryyyyyrryrfdvfdddooffdv.....",
      ".vfrflrdfryrrrfrrffddfffdvdfrd......",
      "..drdryrffrfrffrfffvdffdovfyrd......",
      "..vfrfrrrfdddfffffdoffdodddyyo......",
      "...vfffrrrrrfffffdodfddkfyvryo......",
      "....oddfffrfdfffddodfd..dydlyo......",
      ".....ovddddddddvv..dfd..vlffyo......",
      "........oooovdd....dddv..ffvyf......",
      "..........ovok.....vdfv..vfoyyf.....",
      "..........oddv......dfv...vvfyyd....",
      "..........ddffv.....ofdd.....oo.....",
      "...........ooo......odffv...........",
      ".....................vddd..........."
    ]
  },
  {
    "key": "diemLong-shiny",
    "line": "lua",
    "stage": 3,
    "size": 48,
    "palette": "fireShiny",
    "grid": [
      "..........r................................",
      "..........ry...............................",
      ".......r..yy..yr...........................",
      "....d..Y.ryy.yy............................",
      "....oo.yyryrdyYdo..........................",
      "...voo.yyyyyyyvooyyr...................yyd.",
      "...vokyYyyyyyvooryyy....dd............dyd..",
      "...vorYYYYYyvoooryd....ryrrd..........ryr..",
      "...okyYhYyrookkoyrrv.kyyyrrrd..........yy..",
      "...oorYYyrookrkkyyyrryyrrdddrrd.......dyyr.",
      "...ookyyrookrkoyyyyyyyrrko..d.......dryyyy.",
      "...okrvvoookrkkyrrryrrrkv........yyyyyyyyyd",
      "..vvyrovvvookoryrrkkkkvd........ryyyyyyyyd.",
      "..dkykrryrooovrrryro..d......d..yyyyyyyrd..",
      "..dvvrrodroookkorryrvdkd....ry.ryyyyyrkd...",
      "..vvvvttrvoooookkkryrrv.....yr.ryyyyrrk...d",
      ".vvvoooovooooooovovkkd....ryyy.ryyyrrro..rd",
      "vvvoooooooooooov...vv...ryyyyyryyyyrrrv..dd",
      "vooooooooooooo.........ryyyyyyyyyryyrrkd.rd",
      ".oooooooooooo..........yyyrryyyyyryyrrrvdrv",
      "......ooooooo.........dyyyryyyyyyryyrrrrrrv",
      "......oookooov........ryyryyyyyrrryyrryrrrv",
      ".....vkokroooo........vyyryrrrrrrryyryrkrkv",
      "....vrrrrrkoooo........rrrrrrrrrryyryrkkoo.",
      "....vrrrrrrooooo....oookrrrrrrrrryyrykkk...",
      "...vryryrrrkoooooooovvooorrrrrryyyrryrkk...",
      "...vryryrrrkoooooovddvoooodrrrryyrryyrrvdd.",
      "..vkryrrkkrroooooovoooooooorrrrrrrryyrkvdv.",
      "..drrrrrkoorkoooooooooooooorrrrrryyyyrvfrv.",
      "..vkokrkkookkooooooooooooooorrryryyrrkvrko.",
      "..vookrrkoooooooooooooooooookrrrrrrrrrrkv..",
      "..d..kkkkoooooooooooooooooookkkrrrkkkrkv...",
      ".....ookkoooooooooooooooooooookkkkkkkkv....",
      ".....oookooooooooooooooooooo..vkkkkkvv.....",
      "......ookkoooooooooooooooooo...oooov.......",
      "......oookoovvd..ooooooooooooo.............",
      "......vookkovrkv.voooo.ooooooo.............",
      ".......ookkvrrdd..ooood.vooooov............",
      ".......dkkvrykv...oooo....oooov............",
      "........vkkyyrd...oooo.....ooov............",
      "........okkyrv....ooo......doov............",
      "........okryd....oooo......dvov............",
      "........okryv...doooo......ddvv............",
      "........vkyyo...okko......ddddd............",
      ".......okryr....ooo.......fffdv............",
      "......vkryyd..............ffrd.............",
      "......vdrrrv...............dd..............",
      ".......vvvo................................"
    ]
  },
  {
    "key": "giot",
    "line": "thuy",
    "stage": 1,
    "size": 32,
    "palette": "water",
    "grid": [
      "................................",
      "................................",
      "................................",
      ".............daaaaAo............",
      ".............aahlCo.............",
      "............hahlllo.............",
      "..........ffClfffffd............",
      ".......ffflllllllffdd...........",
      ".....dflllllllllllllfd.......ff.",
      ".....flhhhBllllllllllfd....flhhd",
      "....fhChhhhllllhCCChllfd..dhhhhd",
      "...lBCbbhhBlllllhhCaChlfd.fhlCAd",
      "..flhhbhhBlllllllllhaaahddllhCf.",
      "..fBhhhhBlllllllllllllhCAdllhld.",
      ".fllBhBlllhllllhlllllllllfllhlo.",
      ".lfllllllCaahllClhllCCClllllhd..",
      "olflllllhCdAallhClCllhCChlllhd..",
      "okdlllllhfdkahllClCllCllllflhd..",
      "ddllllllhdkfalllChhlllllfoflllo.",
      "dllllllllhAahllhhlllllfldkfllfo.",
      "ddlllBlflllllllhlllllfffdddflhf.",
      ".dfffffllfflllllllfffflf..ddfld.",
      ".dflllhhhlllllllfflfflfd...dood.",
      "..ddlhhhhhlllfffllllff..........",
      "..fddflBBlllllfflllllf..........",
      ".oflfddfflllllldolhhCld.........",
      "..fdd..ddfffffdoodlaaad.........",
      "..................ddddd.........",
      "................................",
      "................................",
      "................................",
      "................................"
    ]
  },
  {
    "key": "suoiVot",
    "line": "thuy",
    "stage": 2,
    "size": 40,
    "palette": "water",
    "grid": [
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      ".....................ffd................",
      "..................faacl.................",
      "................dAaCChd.................",
      "...............faClhCA...............ffd",
      "..............AahlCCCd.............ofChd",
      ".............AallChCCf......d.....dlCad.",
      ".............aCflllaCf....flf....dlCaA..",
      "............aaflflhlhAo..dhCd...dfChad..",
      "..........oAalffffddddo.dlCA....dllCao..",
      "........dddaadddddffdffdoflf...ofllaA...",
      ".......dffAAodfflffflhCllfdoo..dfllaf...",
      ".....odflfddffffhlfhClllllllfdodffaA....",
      "....ddllllfffffAllCCalffffflffffdlaA....",
      "...ddBbBlfffffaAlhlfllffChfffllfdfaA....",
      "...olhhlffffdCaffffffffhwcCaAfdffdAao...",
      "..AflllflfffhahllllcCflclfhfffoodfdaf...",
      ".AdfllflffaaaldhfllhCCclffdffd..odlAA...",
      ".AoffffdlaaoAhdlflAdflldddlloo..ddfAad..",
      ".ddfffffwAaoAlffllAdfddddlldad...dodAA..",
      ".offfffaaAAflffflfddfdffhldlaA....ooodo.",
      "fhfdddfdffflCfdldoodflhhlddflhd.....oooo",
      "dhChhlfffdfdllffoofddllfo..oddd.........",
      ".dfhhhhhllhhCChldfffdddod...............",
      "..fffflllhhhChhClfffllllld..............",
      "...doflhhhhhhhhlfdAfflhhCl..............",
      "..dlffdddddddddd..fAflhCCCf.............",
      ".daAfd.............faChlCccld...........",
      ".odd................dAAAccCcCf..........",
      "......................ooAfffff..........",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................"
    ]
  },
  {
    "key": "trieuLong",
    "line": "thuy",
    "stage": 3,
    "size": 48,
    "palette": "water",
    "grid": [
      "..............l.......................",
      ".............ld.......f...............",
      "............lAd.....flf...............",
      ".......llf..Alhfldflhlf...............",
      ".....fll...fAhChlCChAlCl..f...........",
      "...........AlChhlCCllhCCBhl...........",
      "...........AlClllCBllCChhlf...........",
      "..........AllhlflhlAfhhlAlC...........",
      "..........AflllfhllflhllfhCld.........",
      ".........lAfhlAfhlAfhllflChllf........",
      ".......A.AllllfflffflfAdlhlAl.........",
      "......a..afllffffAffflfflfffCf........",
      "........ladlflffdddddfdddfflCCf.......",
      "........aAflffodffffffffdddflllf......",
      "........aAffodfffffflffflffdfffd......",
      ".......fafddffflfflflAfflffffdff....f.",
      ".......laodfffffllflflaalfffdfff...Bl.",
      "......daAdfffflfhahfffaahfffllffd..b..",
      "..f..fffdffAhfflCflalCfflllChlffd..h..",
      "ld..dllfllllhllllfflaAfffaaflhfff.lf..",
      "hlldfCallffflllalffAflAfaflfflffffB...",
      "lllfChCllffllfffAAllfffafffAfAAllf....",
      "lffAhlhhlflaflflffAdfffAffdAfddlffd.AA",
      "AlfCBlahflalfflfldAAddffffffddflflf.f.",
      ".ffhhalllaAfldffdffdflllllllfdfffdd...",
      ".dfahlfhadffffffdfflBlfflfllllffdfffd.",
      ".dfAflfaAfAllAdofdfldhcwwCdlllfddflllf",
      ".ffffffAAAffffddfdddflcwwhdfllldfdflhh",
      ".fhlBhlffffdfffdAffllllccffofllfdfofff",
      ".dlffffBCaAlfflCAAfflhhhcdfhfllfffd.l.",
      "...lfAAAlCcldCwwcAahlBlllhcwlllffd..C.",
      "...flaaAhBCacwccwcCAaCCChhwCllldfd..Cl",
      "....llhllbcwacwccwwcCAAllfClllffd...Ah",
      ".....dd.BcwwcacwwwcwwcchhCllhfffd....l",
      ".......lbcwClCChCcwwcwhffdfBldfd.....l",
      "......lbcwwCflChllhcwwwldlBfddd......l",
      "......CbcwcwclBhClllCChlflfddo........",
      "......lbcwcwC..fflllfoflfddff.........",
      ".......lbcwC....dfffdffddddffo........",
      "........lbh......dffddod...fd.........",
      "..............fA..dffdd....d..........",
      ".................flffd........l.......",
      ".................ohld.........l....f..",
      ".................fBhd..hl....f...lB...",
      ".................lllllflbhl.flfllB....",
      "................dffd.....lBllf........",
      "................ffd...................",
      "...............ddd...................."
    ]
  },
  {
    "key": "mam",
    "line": "thao",
    "stage": 1,
    "size": 32,
    "palette": "grass",
    "grid": [
      "..ddddd..............",
      ".Uflflfoo............",
      ".UflfffldU...UdfffdU.",
      "..dllfddfd..ufffflffu",
      "..UfllfdddUudffffflfU",
      "...UdffffdodffllllfUU",
      "....oooodddfdfflfdU..",
      "........oofoooooU....",
      "........kddo.........",
      "........oudo.........",
      "......UddddkU........",
      "....uufllfddUU.......",
      "....fhhhhlllld.......",
      "...fhhhhhlllllM......",
      "..fllhhhhlllllfU.....",
      ".UflllllllllllluU....",
      ".llllllllllllllfU....",
      "olhdllllllfdlllfU....",
      "dfUolllllfCollllMU...",
      "UloollllldoollllMU...",
      "UflflllllfodllffMU...",
      "UdllfffdfllllfffUU...",
      "uoflfddlllllfffmU....",
      ".Udllllllllffffou....",
      "..UodfffffffdddU.....",
      "...okUdddddddofuU....",
      "....ddddddddffffuU...",
      "...olfdfdfllddffdU...",
      "...olfMoofllfkdfdU...",
      "...ofdo.kflfo.UoU....",
      "....UU..ooffU........",
      ".........UUu........."
    ]
  },
  {
    "key": "bupXanh",
    "line": "thao",
    "stage": 2,
    "size": 40,
    "palette": "grass",
    "grid": [
      ".............MmmmmM....................",
      "...........mmPpppPPmm..mmmmmm..........",
      "..........PPmmPPPPmCCmmmPpppPm.........",
      ".........mmmmPmmmmCmmmmCmPppppPM.......",
      "........mmPpppPPPmChhlClMMmmPPPmM......",
      ".......MPPppPPpPPPMmllmmmPPPPmmmm......",
      "......MmPPPPPpPmMMmmMmmmPPPPppPmM......",
      "......MMMmPPmMMMMoMPPPPPmmPPPPppmM.....",
      "...uuudfMmPmMmmmmMomPPPppmMPPPPpPm.....",
      "..UuffdooMmUUoMmMMMmppPPPPmmPppPPmM....",
      "..UUdodfdoddddooMMMmPPPPPPmpPPPPmMo....",
      "...uUdfddfffffdokokMPPPPPPPMuMPPMo.....",
      "..uudfddfffdddouuukmPPmPPPPMooMmoUUU...",
      "..uudfdffdfUkUlluuomPmomPmmMUUoodddUU..",
      "..UdffflfoUUuuuUMMoooooMmMkoUoUddddfdUU",
      "..UoflfdoUullluUMModUUUoooUddddddffffuU",
      ".UuudUUUuuuuuUuuUUoooddUododdddudodfdo.",
      ".uClluulluuUmCuluuUoddfddddooUkko.ok...",
      ".mmuCluluuumPwuuuuUkdffffddfuU.........",
      "uuuCCluulUMmCcuuuuUkofddffdffdk........",
      "ullllluuuuuuCuuuuuuUoUoffffdffUk..uu...",
      "uullluuullluuuuuuuuuUkUffdfddfUU.uuU...",
      ".UuuluuluuuuUUUuuuuuuuUofdffffdUuuuU...",
      "..UUuuUUUUUuuuuuuuuuuuuUodffffdouuuU...",
      "...UoUUUuuuuuuUUuuuuuuuuuUdodfoUuuuU...",
      "....UUuuuuuUUUUuuluuuluuluUUoouUUuUo...",
      ".....UoooooUUUuuuuuuuuuuuuuuUuuuoUU....",
      "......koUUUUuuuuuuuuuuuuuuUuuuuuuoU....",
      "......koUuuuuuuuuuuuuluulluluUuuuU.....",
      "......kUUUulluuuuuuuuuuUuuuuUUuuuU.....",
      "......kUuUUuuuuuUuuuuuuUuuuuUuuuuUU....",
      "......ouuuUoUuuuUuuuuuuuUuuUUuuuuUU....",
      ".......UuuuUoUUUUuluuluuoUUUuuuuuUU....",
      ".......ouuuuUooUoUluuuUuoooUuuuuuUU....",
      ".......ouuuuUU.UuUuuuuuuo..uUuuuuUU....",
      "......oUuuuuUU..ukUuuuuuu.UUuuuuuU.....",
      "......UCuCuuU....UUuuuuU...uuUuUu......",
      "......UuUuUU.....uuuuuuU....UUUU.......",
      ".......UUUU......uCuCuCo...............",
      ".................uUUUUuU..............."
    ]
  },
  {
    "key": "coThuLinh",
    "line": "thao",
    "stage": 3,
    "size": 48,
    "palette": "grass",
    "grid": [
      "..........o....UUduU..................",
      ".........UuuUuuuffdUU.................",
      "....UUU.Uffffddfffffuu.uuu............",
      "..UuuddUdfffffduffffdUodfdU...........",
      ".uudfffddffdfddffffdUUdfffduu.........",
      ".uffffffddddddffffddUUdfffduUU........",
      ".ddfffffuddffffffffdUUUdddUUUU........",
      "UuudffffdffffddffffdUUUddUUUUU........",
      ".uuddffddufddUUddfddUUdffdUUUU........",
      "udfdfffdUUddUUoUddUUUdffffdddo........",
      "UfffddfuoooUUUooUoooUdfdfdfffUU.......",
      "UdfdUUdUoMMooUUokMoooUdUoouddoU.......",
      ".UdUoooUoMMooUooMooUooMMUUUUoo........",
      "..UoUoMoooMMoooMMkUooMMoUUUUoU........",
      "...oooMMokMmMMMmMoooMmkoUUoUUUU.......",
      "...UUUoMMoMmMMmmMoMmMokooMUUUUUU......",
      "..oUUUUoMmmmMmmmMMmMooMMkoooUUu.......",
      "...UUUUokmmmmmmmmMMMMMokoooUoU........",
      "....ookUoMmmmmmmMMMMMooooooU..........",
      ".......koommmMmMkkmMMkoUUUU...........",
      ".........UoMmMkMkMmMMUUU.......UUUUuU.",
      ".........UMMmmMMMmmMMM........UdduddUU",
      ".........UMmmmmmmMmMMMu.......udfdfdo.",
      "........UoMMmmMmMMmmmmMU..U..UdddddUU.",
      "......UMMMkkMokMkomMmmmmoMM..UUUUddUUU",
      ".....UMmMokkkkkkkkMMoMMmMMM...UUooUUoU",
      "...UmmmmMoMMokmoMMMMMkMMMmMM...UokooU.",
      "..UmmmmMMoMmMMmMMmmMMokMmMMM...UMo....",
      ".UmmmmMMMkmmmmmmmmmMMoMmmmMoo..MMo....",
      ".mmMmMMouuMmmmmmmmmoommmmmMkMMMMo.....",
      "UMmMMMMoummmmmmmmmMMmmmmmMMoMMooo.....",
      "MMMoMMM..MmmmmmmmmoMoMMmmMMoMMkM......",
      "oMMokMM..MmmmmmmmmMoMoMmMMoMMMMM......",
      "oMMMoMU..MmmmmMmMmMMMMmMMMoMMMMo......",
      "ooMMUU..UMMMmmMMMmMMoMMkoMkMMMMM......",
      "ooo.....MMMMMmMMMMmMokooMoMMMMMM......",
      "........MmMMMMMMMMmmMMMooMMMMMMMo.....",
      ".......MmmMoMMMMMMmmmMMMMMoMMMMMo.....",
      "......UmmmMMoooMMMmmmMMMoUuMMMMMMo....",
      "......MmmmmMMoUMMMmmmmMMM..UMMMMMo....",
      "......MMmmMMo...UMmmmmMMMU..ooMooM....",
      ".....UMmmMMMM....oMmmMoMMU.UoMMMMMU...",
      ".....MMMmmMMM....oMmmMMMMU.UoMMMMMM...",
      "....UMMommMMoU...MmMmMMMMk.MooMMoMkU..",
      "...UMMoMMMoMoU..UMMMMmMMMoUUoUMM.UU...",
      "......oooU..U...kMMMMmMoMoM...........",
      "................UU.oMmMooo............",
      "....................kM................"
    ]
  }
];
