/* ============================================================
   SPRITE DATA — Pet Pomodoro (chuẩn skill pet-sprite-art)
   AUTO-GENERATED bởi scripts/gen-sprites.py — đừng sửa tay,
   sửa definition trong script rồi chạy lại: python3 scripts/gen-sprites.py
   Stage 1 = 32×32 · Stage 2 = 40×40 · Stage 3 = 48×48
   Shiny = cùng grid + palette thay thế (fireShiny).
   ============================================================ */

globalThis.SPRITE_DATA = {
  meta: {
    lines: {
      lua: { ten: "Lửa", stage: ["Tàn Lửa", "Bồng Bột", "Diễm Long"] },
      thuy: { ten: "Thủy", stage: ["Giọt", "Suối Vọt", "Triều Long"] },
      thao: { ten: "Thảo", stage: ["Mầm", "Búp Xanh", "Cổ Thụ Linh"] }
    },
  },
  palettes: {
    fire: {
      o: { hex: "#4A1410", ten: "viền nâu đô" },
      d: { hex: "#7E1F16", ten: "đỏ sâu" },
      f: { hex: "#B5382A", ten: "đỏ thân" },
      l: { hex: "#E06038", ten: "đỏ cam sáng" },
      h: { hex: "#F5A05A", ten: "highlight cam" },
      c: { hex: "#F2E5C8", ten: "kem mõm ngực" },
      C: { hex: "#D9BE9A", ten: "kem bóng" },
      v: { hex: "#5A1810", ten: "viền lửa" },
      r: { hex: "#D9452B", ten: "lửa cạnh" },
      y: { hex: "#F28C28", ten: "lửa giữa" },
      Y: { hex: "#F7C948", ten: "lửa sáng" },
      W: { hex: "#FFF6D8", ten: "lõi lửa" },
      k: { hex: "#143C3C", ten: "mắt tối" },
      t: { hex: "#3FA8A0", ten: "mống teal" },
      w: { hex: "#FFFFFF", ten: "glint" },
    },
    fireShiny: {
      o: { hex: "#232B36", ten: "viền xám đậm" },
      d: { hex: "#46566E", ten: "thép sâu" },
      f: { hex: "#8C9BB0", ten: "thép thân" },
      l: { hex: "#B8C4D4", ten: "thép sáng" },
      h: { hex: "#DDE6EE", ten: "highlight bạc" },
      c: { hex: "#E8E9F2", ten: "kem lạnh" },
      C: { hex: "#BFC2D4", ten: "kem bóng lạnh" },
      v: { hex: "#1E3B3C", ten: "viền lửa teal" },
      r: { hex: "#1F8F84", ten: "teal cạnh" },
      y: { hex: "#2EC4B6", ten: "teal giữa" },
      Y: { hex: "#7FE8DE", ten: "teal sáng" },
      W: { hex: "#E8FFF9", ten: "lõi teal" },
      k: { hex: "#143C3C", ten: "mắt tối" },
      t: { hex: "#E8B84A", ten: "mống vàng" },
      w: { hex: "#FFFFFF", ten: "glint" },
    },
    fireSick: {
      o: { hex: "#5A4438", ten: "viền nhợt" },
      d: { hex: "#8A6A5C", ten: "đỏ nhạt sâu" },
      f: { hex: "#B08A76", ten: "đỏ nhạt thân" },
      l: { hex: "#C9A88E", ten: "sáng nhợt" },
      h: { hex: "#E0C8AC", ten: "highlight nhợt" },
      c: { hex: "#E5DCC8", ten: "kem nhợt" },
      C: { hex: "#C2B49A", ten: "kem bóng nhợt" },
      g: { hex: "#8C8C8C", ten: "khói" },
      G: { hex: "#6E6E6E", ten: "khói đậm" },
      k: { hex: "#4A4038", ten: "mắt nhắm" },
      t: { hex: "#8CA8A0", ten: "mống nhợt" },
      w: { hex: "#FFFFFF", ten: "glint" },
    },
    water: {
      o: { hex: "#16283E", ten: "viền nave" },
      d: { hex: "#24365C", ten: "navy sâu" },
      f: { hex: "#35507E", ten: "navy thân" },
      l: { hex: "#5B7CB0", ten: "navy sáng" },
      h: { hex: "#8FA8CE", ten: "highlight" },
      c: { hex: "#C7D8EE", ten: "bụng sáng" },
      C: { hex: "#9FB4D0", ten: "bụng bóng" },
      a: { hex: "#E8C860", ten: "vây vàng" },
      A: { hex: "#B89030", ten: "vây vàng đậm" },
      b: { hex: "#A8D8F0", ten: "bọt sáng" },
      B: { hex: "#5FA8CC", ten: "bọt đậm" },
      k: { hex: "#101820", ten: "mắt tối" },
      t: { hex: "#F0C040", ten: "mống vàng" },
      w: { hex: "#FFFFFF", ten: "glint" },
    },
    grass: {
      o: { hex: "#1E3A1C", ten: "viền rêu đậm" },
      d: { hex: "#3E7A34", ten: "xanh sâu" },
      f: { hex: "#5FA84A", ten: "xanh thân" },
      l: { hex: "#93D06E", ten: "xanh sáng" },
      h: { hex: "#B8E88A", ten: "lá non" },
      c: { hex: "#D8EFC0", ten: "sáng nhạt" },
      C: { hex: "#A8C888", ten: "bóng nhạt" },
      u: { hex: "#4E8A5E", ten: "nụ/hạt" },
      U: { hex: "#37634A", ten: "nụ đậm" },
      p: { hex: "#F0A0B8", ten: "cánh hoa" },
      P: { hex: "#D06890", ten: "cánh đậm" },
      m: { hex: "#8A6242", ten: "thân cây" },
      M: { hex: "#63452E", ten: "thân cây đậm" },
      k: { hex: "#142014", ten: "mắt tối" },
      w: { hex: "#FFFFFF", ten: "glint" },
      R: { hex: "#D93A2A", ten: "mắt đỏ" },
      e: { hex: "#FF8A4A", ten: "than hồng" },
    },
    egg: {
      o: { hex: "#4A3C30", ten: "viền nâu" },
      c: { hex: "#F7E7CE", ten: "vỏ kem" },
      C: { hex: "#DEC29B", ten: "vỏ bóng" },
      e: { hex: "#FFF8EA", ten: "vỏ sáng" },
      y: { hex: "#F5B840", ten: "vân vàng" },
      Y: { hex: "#FFDD7C", ten: "vân sáng" },
      W: { hex: "#FFF7DB", ten: "tâm vân" },
    },
  },
  grids: {
    trungEgg: { line: "chung", stage: 0, size: 32, palette: "egg", grid: [
          "................................",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................",
          "...............oo...............",
          ".............ooccoo.............",
          "............oeeeecco............",
          "...........oeeecccccCo..........",
          "..........oeeccccccccCo.........",
          ".........oecccyycccccCo.........",
          ".........oeccyYyyccccCo.........",
          ".........oeccyYWWyccCCo.........",
          ".........oeccyYYyccccCo.........",
          ".........oecccyycccccco.........",
          ".........oeccccccccccCo.........",
          ".........oeccccccccccCCo........",
          "..........occcccccccCCo.........",
          "..........occccccccCCCo.........",
          "...........occcccCCCCo..........",
          "............occcccCCo...........",
          ".............ocCCCo.............",
          "..............oooo..............",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................"
    ] },    tanLua: { line: "lua", stage: 1, size: 32, palette: "fire", grid: [
          "................................",
          "................................",
          "......oo........oo..............",
          ".....oddo......oddo.............",
          "....oddo........oddo............",
          "....oddoooooooooddo.............",
          "....ollfffdddfffffddo.....vrv...",
          "....olfffdddddffffdo....vryYyrv.",
          "....oddddfffddddfffo...vryYYyrv.",
          "....owkkkfffwkkkfffo..vryYWYyrv.",
          "....okttkfffkttkfffo.vryYWWYyrv.",
          "....okttkfffkttkfffo.vryYWWYyrv.",
          "....okkcccfffffffffo.vryYWWYyrv.",
          "....occocffffffffffo.vryYWYyrv..",
          ".....ocfcfcffffffdo.vryYWYrv....",
          "......offcccffffdo.vryYWYrv.....",
          ".......occccfffdoryYWYyrv.......",
          "........occccfdoryYWYyrv........",
          "........occccfdoryYWYyrv........",
          ".......occcffffddoyYWYyrv.......",
          ".......occcffffddoyYWYyrv.......",
          "........occcfffdoryYYrv.........",
          "........offfffddovrrv...........",
          ".........offffddo...............",
          ".........offo.offo..............",
          ".........oddo.oddo..............",
          ".........oooo.oooo..............",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................"
    ] },    tanLuaBack: { line: "lua", stage: 1, size: 32, palette: "fire", grid: [
          "................................",
          "................................",
          "......oo........oo..............",
          ".....oddo......oddo.............",
          "....oddo........oddo............",
          "....oddooooooooooooo............",
          "....oddffffffffffddo....vryYyrv.",
          "....odfffffffffffddo...vryYWYrv.",
          "....offffffffffffddo..vryYWYyrv.",
          "....offffffddffffddo..vryYWYyrv.",
          "....offffffffffffddo.vryYWWYyrv.",
          "....offffffffffffddo.vryYWWYyrv.",
          "....offfffddfffffddo.vryYWYyrv..",
          "....offffffffffffddo..vryYWYrv..",
          ".....ofdffdfdffdo.fo...vryYrv...",
          "......ofdfdffdfdo.yYWYrv........",
          ".......ofdffdfdoryYWYrv.........",
          "........ofdfdfdoryYWYrv.........",
          "........offffddoryYWYyrv........",
          ".......offfddfddoryYWYyrv.......",
          ".......offfddfddoryYWYrv........",
          "........offfddoyYWYrv...........",
          "........offffddoyYWrv...........",
          ".........offfddo................",
          ".........offo.offo..............",
          ".........oddo.oddo..............",
          ".........oooo.oooo..............",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................"
    ] },    tanLuaOm: { line: "lua", stage: 1, size: 32, palette: "fireSick", grid: [
          "................................",
          "................................",
          "................................",
          ".......oo......oo...............",
          "......oddo....oddo..............",
          ".....oddooooooooo...............",
          ".....ollffffffffddo.....gGg.....",
          ".....olfffffffffddo....gGgGg....",
          ".....okk.fffkk.fffo...gGgGg.....",
          ".....okk.fffkk.fffo....gGg......",
          ".....occccfffffffffo............",
          ".....ococofffffffffo............",
          "......ocffcffddo................",
          ".......ofcccfffdo...............",
          "........occcffdo................",
          "........occcffdo................",
          ".......occcffddo................",
          ".......occcffddo................",
          "........occffdo.................",
          "........offffddo................",
          ".........offfddo................",
          ".........offooffo...............",
          ".........oddooddo...............",
          ".........oooooooo...............",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................"
    ] },    bongBot: { line: "lua", stage: 2, size: 40, palette: "fire", grid: [
          "........................................",
          "........................................",
          "...........oo.........oo................",
          "..........oddo.......oddo...............",
          ".........oddo.......oddo................",
          "........oddo.......oddo.................",
          "........oddooooooooooooddo..............",
          ".......olffdddddffffffffffo....vrv......",
          ".......olfffffffffffffffddo..vryYyrv....",
          "......olfffffffffffffffffddovryYYyrv....",
          "......odddddfffdddddfffffffovryYWYrv....",
          "......owddddfffwddddfffffffovryYWYrv....",
          "......oktttkfffktttkfffffffovryYWYrv....",
          "......oktttkfffktttkfffffffovryYWYrv....",
          "......okkkkkfffkkkkkfffffffovryYWYrv....",
          "......okkcccccfffffffffffffovryYWYrv....",
          "......occcocffffffffffffffo.vryYWYyrv...",
          ".......ocfcfcffffffffddddddovryYWYyrv...",
          "........occccfffffffffddddo.vryYWYyrv...",
          "........occccccfffffffdddddoryYWYyrv....",
          ".......occcccffffffffddddddoryYWYrv.....",
          ".......occcccffffffffddddddoryYWYrv.....",
          ".......occccccfffffffddddddoryYWYrv.....",
          ".......occccccfffffffddddddoryYyrv......",
          ".......occccccfffffffddddddoryYyrv......",
          ".......occccfffffddd.ddddddoryYrv.......",
          ".......occccfffffddd.ddddddoryrv........",
          "........occcfffffdddddddddo.............",
          "........occcffffddddddddddo.............",
          ".........occffdffddddddddo..............",
          "..........offo......offo................",
          "..........oddo......oddo................",
          "..........oooo......oooo................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................"
    ] },    diemLong: { line: "lua", stage: 3, size: 48, palette: "fire", grid: [
          "................................................",
          "................................................",
          "................................................",
          "................................................",
          "................................................",
          "..............oo........oo......................",
          ".............oddo......oddo.....................",
          "............oddo......oddo......................",
          "............oddo.....oooooooo...................",
          "...........ollfffdddddffffffddo.....vrv.........",
          "...........olffffffffffffffffddo...vryYyrv......",
          "..........olffffffffffffffffffddo.vryYYyrv......",
          "..........oddddddfffddddddddddddovryYWYrv.......",
          "..........owdddddfffwdddddddddddovryYWYrv.......",
          "..........oktttkkfffktttkkddddddovryYWYrv.......",
          "..........oktttkkfffktttkkddddddovryYWYrv.......",
          "..........okkkkkkfffkkkkkkddddddovryYWYrv.......",
          "..........okkccccccccfffffffffddovryYWYrv.......",
          "..........occccccocfffffffffffddovryYWYyrv......",
          "...........ocfcfcfffffffffffffddovryYWYyrv......",
          "............occccffffffffffffdddovryYWYyrv......",
          ".............occccccffffffffddddoryYWYyrv.......",
          ".............occccccffffffffddddoryYWYyrv.......",
          "............occcccffffffffffdddddoryYWYrv.......",
          "...........occccffffffffffffddddddoryYWYrv......",
          "..........occccfffffffffffffdddddddoryYWYrv.....",
          "..........occccfffffffffffffdddddddoryYyrv......",
          "..........occcccffffffffffffdddddddoryYyrv......",
          "..........occcffffffffffffffdddddddoryYrv.......",
          "..........occffffffddd..ddddddddd.o.ryrv........",
          "..........occfffdffdddd..ddddddddoyYrv..........",
          "...........occffddffddd.ddddddddoyrv............",
          "............ocffddffddd.ddddddo.................",
          "............offfddffddd.ddddddo.................",
          ".............offfddd.ddddddddo..................",
          "...............o....o.....o.....................",
          "..............offo..offo..offfo.................",
          "..............oddo..oddo..oddo..................",
          "..............oooo..oooo..oooo..................",
          "................................................",
          "................................................",
          "................................................",
          "................................................",
          "................................................",
          "................................................",
          "................................................",
          "................................................",
          "................................................"
    ] },    giot: { line: "thuy", stage: 1, size: 32, palette: "water", grid: [
          "................................",
          "................................",
          "................................",
          "..............b.................",
          ".............bbb................",
          "............bbBbb...............",
          "............bbBbb...............",
          "...........obBBBbo..............",
          "..........oBBBBBBo..............",
          "......oooooooooooooo............",
          ".....odddddddddddddo............",
          "....odddddddddddddddo...........",
          "....odkkkkffffdddddddo..........",
          "....odwkkkffffdddddddo..........",
          "....odkttkffffdddddddoa.........",
          "....odkkkkffffdddddddoaa........",
          "....occoccccdddddddddoaAa.......",
          "....occcccaAccdddddddoaAAa......",
          "...occcccccccccccccco.aAAa......",
          "...occcccccccccccccco.aAAa......",
          "...occcccccccccccccdoaAa........",
          "....occccccccccccccoaa..........",
          "....occccccccccccccoa...........",
          ".....occcccccccccco.............",
          "......occcccccccco..............",
          "........ooooooooo...............",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................",
          "................................"
    ] },    suoiVot: { line: "thuy", stage: 2, size: 40, palette: "water", grid: [
          "........................................",
          "........................................",
          "..................a.....................",
          ".................aa...............bb....",
          ".................aAa...............b....",
          "................aAAa.............bB.....",
          "................aAAa..............bB....",
          "...............aaAAa...............b....",
          "...............aaAAa.............bBb....",
          "..............aaaAAaa...................",
          ".............aaaaAAaaaa.................",
          "............aaaaaAAaaaaa................",
          "..............ooooooooooo...............",
          "..........oddddddddddddddddo............",
          ".......odddddddddddddddddddddoa.........",
          ".....oddddddddddddddddddddddddoaa.......",
          "....odddddddkkkkkdddddddddddddoaAa......",
          "...oddddddddwkkkkddddddddddddddoaAAa....",
          "...oddddddddkttkkddddddddddddddoaAAa....",
          "..odddddddddkkkkkddddddddddddddoaAAa....",
          "..oocodddddddddddddddddddddddddoaaAa....",
          "..occccdddfffffffffffffffffffffoaAAa....",
          "..occcccaAcccffffffffffffffffffoaaAa....",
          "...occccccfffffffffffffffffffffoaaAa....",
          "...occccccBfffBffffffffffffffffoaAa.....",
          "...occcccffffBfffffffffffffffffoaa......",
          "....occccffffffffffffffffffffffo.a......",
          ".....occcffffffffffffffffffffffo........",
          "......occcffffffffffffffffffffo.........",
          "........occffffffffffffffffffo..........",
          "..........occfffffffffffffffo...........",
          ".............offffffffffffo.............",
          "................oooooooo................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................"
    ] },    trieuLong: { line: "thuy", stage: 3, size: 48, palette: "water", grid: [
          "................................................",
          "................................................",
          "................................................",
          "....................a......................bb...",
          "...................aa.....................bBb...",
          "...................aAa......................b...",
          "..................aAAa...................bBb.b..",
          "..................aAAa..................bB....b.",
          ".................aaAAaa....................BbB..",
          "................aaaAAaaa........................",
          "...............aaaaAAaaaa................bBb....",
          "..............aaaaaAAaaaaa......................",
          ".............aaaaaaAAaaaaaa.....................",
          "............aaaaaaaAAaaaaaaa....................",
          "....oooooooooooooooooooooooooooooooooooo........",
          "...oddddddddddddddddddddddddddddddddddddoB..bB..",
          "...odddddddddkkkkkdddddffffffffffffffff.o..bBb..",
          "...odddddddddwkkkkdddddfffffffffffffffffo.bb..b.",
          "...odddddddddkttkkdddddfffffffffffffffffob......",
          "...odddddddddkkkkkdddddfffffffffffffffffo.......",
          "...odddddddwwdddddwwdddfffffffffffffffffo.......",
          "...odddddddcccccocccdddfffffffffffffffffo.......",
          "...occcccccccccccccccccfffffffffffffffffo.......",
          "...occcccccccaAccffffffffBffBfffffffffffo.......",
          "..o.cccccccccaAAaccffffffBfBffffffffffffo.......",
          "..o.cccccccccaAAaccfffffffffffffffffffffo.......",
          "..o.ccccccccccffffffffffffffffffffffffffo.......",
          "..o.ccccccccccffffffffBfffBff.ffffffffffo.......",
          "..o.ccccccccccffffffffffffffffffffffffffo.......",
          "..o.cccccccccfffffffffffffffffffffffffffo.......",
          "...occcccccccfffffffffffffffffffffffffffo.......",
          "...occccccccffffffffffffffffffffffffffffo.......",
          "....occccccccfffffffffffffffffffffffffffo.......",
          ".....occccccccffffffffffffffffffffffffffo.......",
          "......occccccccfffffffffffffffffffffffffo.......",
          ".......occccccccffffffffffffffffffffffffo.......",
          "........occccccc.fffffffffffffffffffffffo.......",
          "..........occcccccffffffffffffffffffffffo.......",
          "............occcccc.ffffffffffffffffffffo.......",
          "..............occ.ffffffff.ddddddddfffffo.......",
          "................oc.ffffff.ddddddfff.o...........",
          "..................oooooooooooooooo..............",
          "................................................",
          "................................................",
          "................................................",
          "................................................",
          "................................................",
          "................................................"
    ] },    mam: { line: "thao", stage: 1, size: 32, palette: "grass", grid: [
          "................................",
          "................................",
          "............oo....oo............",
          "...........ohho..ohho...........",
          "..........ohhho..ohhho..........",
          "..........ohhho..ohhho..........",
          ".........ohhhho..ohhhho.........",
          ".........ohhho....ohhho.........",
          ".........ohho..oo..ohho.........",
          "..........oho..oo..oho..........",
          "...........oooooooooo...........",
          "..........oduuuuuuuuUo..........",
          ".........odduuuuuuuUUo..........",
          "........odduuuuuuuuuUUo.........",
          "........oduuuuuuuuuuUUo.........",
          "........odukkkuuukkkUUo.........",
          "........oduwkkuuuwkkUUo.........",
          "........odukkkuuukkkUUo.........",
          "........odukkkuuukkkUUo.........",
          "........odppuuuoouuppUo.........",
          "........odduuuuuuuuuUUo.........",
          "........odduuuuuuuuuUUo.........",
          "........odduuuuuuuuuUUo.........",
          "........oduuuuuuuuuuUUo.........",
          ".........oduuuuuuuuUUo..........",
          "..........oduuuuuuuUo...........",
          "............oooooooo............",
          "...........offo...offo..........",
          "...........oddo...oddo..........",
          "...........oooo...oooo..........",
          "................................",
          "................................"
    ] },    bupXanh: { line: "thao", stage: 2, size: 40, palette: "grass", grid: [
          "........................................",
          "........................................",
          "........................................",
          "..........................pp.pp.........",
          ".........................pPPpp..........",
          "........................pPPPPpo.........",
          "........................pPPPPPPp........",
          ".......................pPPpPPPPp.o......",
          ".......................pPpUUUUUppo......",
          ".......................oUUUUUUUUUoo.....",
          "......................oUuUUUUUUUUoo.....",
          "......................oUUuUUUUUUUoo.....",
          "......................oUUUUuUUUUUoo.....",
          "......................oUUUUUUuUUUo.o....",
          ".....oooooooooooooo...oUUUUUUUUUUo.o....",
          "....oddffffddffffffffooUUUUUUUUUo.o.....",
          "....odffffffddddffffffffooUUUUUUUUo.....",
          "...odfffffffddddffffffffooUUUUUUUoo.....",
          "...odwkkk.fffoccccccdddd.ooUUUUUUoo.....",
          "...odwkkffffoccccccddddd.ooUUUUUo.o..o..",
          "...odkkkffffoccoo.ccdddd.o.oUUUUo.o..oh.",
          "...odkkkfffffcccccccdddd.o..oUUo..o.ohho",
          "...odccccccoccccccccddddd.o...oUUo.o..ho",
          "...occccccccccccccccccddddo...oUo.o...o.",
          "...occccccccccccccccccccddddd.o...o.....",
          "...occcccccccccccccccccccddddo....o.....",
          "...odccccccccccccccccccccccdddo...o.....",
          "...oddccccccccccccccccccccddddo...o.....",
          "...oddccccccccccccccccccccccddo...o.....",
          "...oddccccccccccccccccccccco..oo..o.....",
          "....odccccccccccccccccccccco...o..o.....",
          ".....odcc.cccccccccccc..oo..o..o..o.....",
          ".......ooooooooooooooo..o..o..o...o.....",
          "......o.ccoo.........o..o..o..o...o.....",
          "......o..o..........o..oo...o..o........",
          ".....oo..oo.........oo..oo..oo.oo.......",
          "........................................",
          "........................................",
          "........................................",
          "........................................"
    ] },    coThuLinh: { line: "thao", stage: 3, size: 48, palette: "grass", grid: [
          "..........ooooffhllllllllllllllhfffoooo.........",
          ".......ooofffhhhhhhhllllllllhhhhhhhffffooo......",
          "......offfffhhhhhhhhhllllllhhhhhhhhhffffffo.....",
          "....oofffffhhhhhhhhhhhllllhhhhhhhhhhhffffffoo...",
          "...offffffffhhhhhhhhhllllllhhhhhhhhhlffffffffo..",
          "...offfffffffhhhhhhhlllldlllhhhhhhhlfffffffffo..",
          "..offfffffffffldddddddddddddddddddlfffffffffffo.",
          "...offffffffdddddddddddddddddddddddddffffffffo..",
          "...offffffdddddddddddddddddddddddddddddffffffo..",
          "....offffdddddddddddddddddddddddddddddddffffo...",
          "....offfffdddddddddddddddddddddddddddddfffffo...",
          ".....oofffffdddddddddddddddddddddddddfffffoo....",
          ".......oooofoofdddddddddddddddddddfoofoooo......",
          "...........o.ommmMmmmMmmdmmMmmmMmmo..o..........",
          ".............ommmMmmMMmmmmMMmmmMmmo.............",
          ".............ommmmMMmmmmmmmmMMmmmmo.............",
          ".............ommMMmmmMmmmmmMmmMMmmo.............",
          ".............oMmmMmmMMMMMMMMmmmMmMo.............",
          ".............ommmmmmmmmmmmmmmmmmmmo.............",
          "............oommmReRmMmmmmmMReRMmmoo............",
          "...........oddddmRRRmMmmmmmMRRRMddddo...........",
          "......ooooooddddmmmmmmmMMmmmmmmmddddoooooo......",
          ".....ommmmmmmmmdmMmmmMmmmmmMmmmMdmmmmmmmmmo.....",
          ".....ommmmmmmmmdmMmmmMmmmmmMmmmMdmmmmmmmmmo.....",
          ".....ommmmmmmmmmMkkMkkMkkMkkMkkMmmmmmmmmmmo.....",
          ".....ommmmmmmmmmkMMkMMkMMkMMkMMkmmmmmmmmmmo.....",
          ".....ommmmmmmmmmkkkekkkekkkekkkkmmmmmmmmmmo.....",
          ".....ommmmmmmmmmkkkRkkkRkkkRkkkkmmmmmmmmmmo.....",
          ".....ommmmmmommmkMkMkMkMkMkMkMkMmmmommmmmmo.....",
          ".....ommmmmmommmMkMkMkMkMkMkMkMkmmmommmmmmo.....",
          ".....ommMmmmommmmmmmmmmmmmmmmmmmmmmommmMmmo.....",
          ".....ommmmmmommmmMmmmMmmmmmMmmmMmmmommmmmmo.....",
          ".....ommmmmmommmmMmmmMmmmmmMmmmMmmmommmmmmo.....",
          ".....ommmmmmommmmmmmmmmmmmmmmmmmmmmommmmmmo.....",
          ".....ommmmmmommmmmmmmmmoommmmmmmmmmommmmmmo.....",
          ".....omMmmmmommmmMmmmmmoommmmmmMmmmommmmMmo.....",
          ".....ommmmmmommmmmmmmmmoommmmmmmmmmommmmmmo.....",
          ".....ommmmmmommmmMmmmmmoommmmmmMmmmommmmmmo.....",
          ".....ommmmmmommmmMmmmmmoommmmmmMmmmommmmmmo.....",
          ".....ommmMmmommmmmmmmmmoommmmmmmmmmommMmmmo.....",
          ".....ommmmmmommmmMmmmmmoommmmmmMmmmommmmmmo.....",
          "...ooommmmmmommmmMmmmmmoommmmmmMmmmommmmmmooo...",
          "..ommmmmmmmmmmmmmmmmmmmoommmmmmmmmmmmmmmmmmmmo..",
          "..ommmommmommmmmmMmmmmmoommmmmmMmmmmmommmommmo..",
          "..ommmommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmommmo..",
          "..omMmommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmomMmo..",
          "...oooomMmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmMmoooo...",
          ".......ooooMmMMoMMmMomMMmoMmMMoMMmMomMooo......."
    ] }
  },
};
